/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    documents: Document;
    categories: Category;
    'packaging-units': PackagingUnit;
    products: Product;
    articles: Article;
    services: Service;
    partners: Partner;
    gallery: Gallery;
    leads: Lead;
    brands: Brand;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'packaging-units': PackagingUnitsSelect<false> | PackagingUnitsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Tài khoản đăng nhập trang quản trị.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Kho file ảnh/video local trên máy chủ (public/media). Ảnh tải trong form sản phẩm/bài viết sẽ lưu vào đây.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Để trống khi tải lên — hệ thống tự lấy từ tên file.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Tải PDF/Word/Excel lên máy chủ (lưu local). Dùng cho tài liệu đính kèm sản phẩm.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * Ví dụ: MSDS phiên bản 2024, Catalogue dòng sản phẩm làm sạch
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Nhóm sản phẩm hiển thị trên cửa hàng.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  slug: string;
  name: string;
  shortName?: string | null;
  tagline: string;
  description: string;
  longDescription: string;
  /**
   * Kéo thả hoặc chọn ảnh/video mới. File lưu trên máy chủ. "Chọn file đã tải trên máy chủ" chỉ tái dùng file local, không phải Cloudinary. Nhớ Lưu thay đổi.
   */
  heroImage: number | Media;
  /**
   * Tên icon lucide-react để render
   */
  iconKey: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quản lý các đơn vị đóng gói sản phẩm (kg, lít, cái, bộ...). Tắt isActive thay vì xóa để không ảnh hưởng sản phẩm đang dùng.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packaging-units".
 */
export interface PackagingUnit {
  id: number;
  /**
   * Ví dụ: Kilogram, Lít, Cái, Bộ
   */
  name: string;
  /**
   * Viết thường, ví dụ: kg, lít, cái, bộ. Dùng để hiển thị trên chip và tự sinh label.
   */
  symbol: string;
  sortOrder?: number | null;
  /**
   * Tắt để ẩn khỏi danh sách chọn khi tạo quy cách mới. Không xóa để bảo toàn sản phẩm cũ.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quản lý danh mục sản phẩm, ảnh, quy cách đóng gói và tài liệu đính kèm.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  slug: string;
  name: string;
  category: number | Category;
  brand?: (number | null) | Brand;
  shortDescription: string;
  longDescription: string;
  /**
   * Kéo thả hoặc chọn ảnh/video mới. File lưu trên máy chủ. "Chọn file đã tải trên máy chủ" chỉ tái dùng file local, không phải Cloudinary. Nhớ Lưu thay đổi.
   */
  heroImage: number | Media;
  /**
   * Kéo thả hoặc chọn ảnh/video mới. File lưu trên máy chủ. "Chọn file đã tải trên máy chủ" chỉ tái dùng file local, không phải Cloudinary. Nhớ Lưu thay đổi.
   */
  galleryImages?: (number | Media)[] | null;
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  composition: string;
  usage: string;
  warning: string;
  /**
   * Thêm từng quy cách. Nhãn hiển thị tự sinh nếu để trống. Ảnh riêng nếu để trống sẽ dùng ảnh hero.
   */
  packagingOptions?:
    | {
        /**
         * Có thể để trống, ví dụ chỉ đơn vị "cái", "hộp". Hoặc nhập "1", "5", "25".
         */
        quantity?: number | null;
        unit: number | PackagingUnit;
        /**
         * Để trống → tự tạo "5 kg", "20 lít". Hoặc nhập "Túi 5 kg", "Thùng 25 kg"
         */
        customLabel?: string | null;
        /**
         * Ảnh riêng cho quy cách này. Để trống → dùng ảnh đại diện sản phẩm.
         */
        variantImage?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Ghi chú ngắn nếu cần, ví dụ: 'Liên hệ để đặt số lượng lớn'
   */
  packaging?: string | null;
  certifications?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Dán/soạn bài giới thiệu có sẵn tại đây (như Word): tiêu đề, đoạn văn, danh sách, chèn ảnh/video, gallery. Không cần làm lại từ đầu — tải ảnh minh họa trực tiếp trong editor.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Upload file PDF/Word cho mỗi tài liệu. Hiển thị thành danh sách tải xuống trên trang sản phẩm.
   */
  attachments?:
    | {
        type: 'msds' | 'catalogue' | 'manual' | 'technical' | 'other';
        /**
         * Ví dụ: "MSDS - Green Oli Degreaser 2024"
         */
        label: string;
        file: number | Document;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Thương hiệu / hãng sản xuất gắn với sản phẩm.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  slug: string;
  name: string;
  tagline?: string | null;
  description?: string | null;
  /**
   * Kéo thả hoặc chọn ảnh/video mới. File lưu trên máy chủ. "Chọn file đã tải trên máy chủ" chỉ tái dùng file local, không phải Cloudinary. Nhớ Lưu thay đổi.
   */
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tin tức và bài viết hiển thị trên website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  slug: string;
  title: string;
  excerpt: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Kéo thả hoặc chọn ảnh/video mới. File lưu trên máy chủ. "Chọn file đã tải trên máy chủ" chỉ tái dùng file local, không phải Cloudinary. Nhớ Lưu thay đổi.
   */
  coverImage: number | Media;
  publishedAt: string;
  author: string;
  category: string;
  readingMinutes: number;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Các dịch vụ công ty hiển thị trên website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  slug: string;
  name: string;
  tagline: string;
  description: string;
  /**
   * Tên icon lucide-react để render
   */
  iconKey: string;
  /**
   * Kéo thả hoặc chọn ảnh/video mới. File lưu trên máy chủ. "Chọn file đã tải trên máy chủ" chỉ tái dùng file local, không phải Cloudinary. Nhớ Lưu thay đổi.
   */
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Logo và thông tin đối tác (banner trang chủ).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  /**
   * Kéo thả hoặc chọn ảnh/video mới. File lưu trên máy chủ. "Chọn file đã tải trên máy chủ" chỉ tái dùng file local, không phải Cloudinary. Nhớ Lưu thay đổi.
   */
  logo: number | Media;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ảnh hoạt động / gallery trang chủ (gắn file từ Ảnh & Video).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  /**
   * Kéo thả hoặc chọn ảnh/video mới. File lưu trên máy chủ. "Chọn file đã tải trên máy chủ" chỉ tái dùng file local, không phải Cloudinary. Nhớ Lưu thay đổi.
   */
  image: number | Media;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Form liên hệ từ website. Chỉ admin xem/sửa/xóa.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  fullName: string;
  email: string;
  phone: string;
  subject?: string | null;
  message: string;
  status: 'new' | 'contacted' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'packaging-units';
        value: number | PackagingUnit;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  shortName?: T;
  tagline?: T;
  description?: T;
  longDescription?: T;
  heroImage?: T;
  iconKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packaging-units_select".
 */
export interface PackagingUnitsSelect<T extends boolean = true> {
  name?: T;
  symbol?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  category?: T;
  brand?: T;
  shortDescription?: T;
  longDescription?: T;
  heroImage?: T;
  galleryImages?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  composition?: T;
  usage?: T;
  warning?: T;
  packagingOptions?:
    | T
    | {
        quantity?: T;
        unit?: T;
        customLabel?: T;
        variantImage?: T;
        id?: T;
      };
  packaging?: T;
  certifications?:
    | T
    | {
        value?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  description?: T;
  attachments?:
    | T
    | {
        type?: T;
        label?: T;
        file?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  excerpt?: T;
  body?: T;
  coverImage?: T;
  publishedAt?: T;
  author?: T;
  category?: T;
  readingMinutes?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  tagline?: T;
  description?: T;
  iconKey?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  tagline?: T;
  description?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}